spring:
  profiles:
    active: release
  main:
    allow-bean-definition-overriding: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

server:
  port: 8080
  servlet:
    context-path: '/circling'

jwt:
  token:
    secret-key: 'secretKey'
    expire-hours: 24
