spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/circling
    driver-class-name: org.mariadb.jdbc.Driver
    username: client
    password: learnit#01

  # jpa설정
  jpa:
    hibernate:
      ddl-auto: update
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
  redis:
    source:
      host: 127.0.0.1
      port: 6379

server:
  port: 1489

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
